# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7d3397721d2b126ca3c01b9cc18dfcfade6254597978dcd476e2ec51391146deefa2acdc925a836e2a63805dceefb33f61d6ac7da02a10916b8118acaf5221b

test:
  secret_key_base: e0bf87d1ffc39f126b790c27d32d14118365eb42c31d13617d1a4eaf4d02e404743bce9a59da633d8de19219e8df7b5471724d559940dced74ff3fb075f80c33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
